apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: flux-ops/ops/external-secrets-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system # reference this repo
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-store
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-operator
  interval: 1m0s
  path: flux-ops/ops/external-secrets-store
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system # reference this repo
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
