apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
spec:
  chart:
    spec:
      chart: redis
      version: 16.12.3
  valuesFrom:
    - kind: ConfigMap
      name: redis-values