apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: APP_NAME-config
spec:
  data:
  - secretKey: mongoUser
    remoteRef:
      key: ENV_NAME/MongoDB/MachineDb
      property: Username
  - secretKey: mongoPass
    remoteRef:
      key: ENV_NAME/MongoDB/MachineDb
      property: Password
  target:
    template:
      data:
        production.yml: |