apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets-operator
spec:
  interval: 1m
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: external-secrets
      version: '0.6.0'
      sourceRef:
        kind: HelmRepository
        name: external-secrets-operator
        namespace: kube-system
      interval: 1m
  values:
    priorityClassName: "system-cluster-critical"
    nodeSelector:
      eks.amazonaws.com/capacityType: ON_DEMAND
    serviceAccount:
      create: true
      name: external-secrets
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::842487502406:role/external_secrets-${cluster_name}"
