---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: simple-python-rest
  namespace: flux-system
spec:
  interval: 1m0s
  path: flux-apps/simple-python-rest/test
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
