---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: test-ingress
  namespace: flux-system
spec:
  interval: 5m0s
  path: flux-ops/ingress/test
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system # reference this repo
