apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-apps
  namespace: flux-system
spec:
  interval: 1m0s
  secretRef:
    name: flux-system
  url: https://github.com/tovern/aws-terraform-eks-example
  ref:
    branch: main
